package org.example.utilidades;

public enum Mensajes {
    //MENSAJES AFILIADO
    ID_NEGATIVO("EL ID NO DEBE SER NEGATIVO"),
    NOMBRES_LONGITUD("LONGITUD NO PERMITIDAD, LONGITUD ENTRE 3 Y 40 CARACTERES"),
    NOMBRE_FORMATO("POR FAVOR REVISE EL FORMATO DEL CAMPO NOMBRES"),
    APELLIDO_LONGITUD("LONGITUD NO PERMITIDAD, LONGITUD ENTRE 3 Y 40 CARACTERES"),
    APELLIDO_FORMATO("POR FAVOR REVISE EL FORMATO DEl CAMPO APELLIDOS"),
    DOCUMENTO_LOGITUD("LONGITUD NO PERMITIDAD, LONGITUD ENTRE 7 Y 10 NUMEROS"),
    DOCUMENTO_FORMATO("POR FAVOR REVISE EL FORMATO DE SU DOCUMENTO"),
    CIUDAD_FORMATO("POR FAVOR INGRESE NUMEROS POSITIVO DE SU CIUDAD ENTRE 0 Y 1123"),
    DEPARTAMENTO_FORMATO("POR FAVOR INGRESE NUMEROS POSITIVOS ENTRE 0 Y 32"),
    FORMATO_CORREO("POR FAVOR REVISE EL FORMATO DE SU CORREO INCLUYA @-NUMERO-LETRAS"),
    LONGITUD_TELEFONO("LONGITUD NO PERMITIDAD, LONGITUD TELEFONO MAXIMO 10 DIGITOS"),
    FORMATO_TELEFONO("POR FAVOR INGRESE SOLO NUMEROS POSITIVOS PARA ESTABLECER SU TELEFENO"),

    //MENSAJES SIGNOVITAL
    LONGITUD_NOMBRESIGNOVITAL("LONGITUD NO PERMITIDAD, LONGITUD DEL NOMBRE 1 Y 100"),
    FORMATO_NOMBRESIGNOVITAL("POR FAVOR REVISE EL FORMATO DEL NOMBRE EXAMEN"),
    FORMATO_UNIDADMEDIDA("UNIDADES DE MEDIDA SOLO ACEPTAN NUMERO POSITIVOS"),

    //MENSAJES EXAMENGENERAL
    LONGITUD_DIAGNOSTICO("LONGITUD NO PERMITIDAD, LONGITUD DEL DIAGNOSTICO ENTRE 15 Y 1000 "),
    FORMATO_DIAGNOSTICO("POR FAVOR REVISE EL FORMATO DEL DIAGNOSTICO"),
    LOGITUD_IMAGEN("LONGITUD NO PERMITIDAD, LOGITUD DE LA IMAGEN ENTRE 5 Y 200"),
    FORMARTO_IMAGEN("POR FAVOR REVISE EL FORMATO DE LA IMAGEN");


    private String mensajes;
    Mensajes(String mensajes) {
        this.mensajes = mensajes;
    }
    public String getMensajes() {
        return mensajes;
    }
    public void setMensajes(String mensajes) {
        this.mensajes = mensajes;
    }
}

